<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="4a44c525-a61f-4c05-a719-fe550ac6c370" name="Jacob@MANTA 2014-01-17 10:59:30" runUser="MANTA\Jacob" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="57ab9ee7-c8ea-4957-ac8f-e61444df60b2">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment userDeploymentRoot="c:\users\jacob\documents\visual studio 2010\Projects\AssertionTestingProject\TestResults" useDefaultDeploymentRoot="false" enabled="false" runDeploymentRoot="Jacob_MANTA 2014-01-17 10_59_30">
      <DeploymentItem filename="c:\users\jacob\documents\visual studio 2010\Projects\AssertionTestingProject\AssertionTestingProject\bin\Debug\AssertionTestingProject.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2014-01-17T10:59:30.0913095-06:00" queuing="2014-01-17T10:59:30.0943120-06:00" start="2014-01-17T10:59:30.0973142-06:00" finish="2014-01-17T10:59:30.2524243-06:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TestAssertFailedExceptions" storage="c:\users\jacob\documents\visual studio 2010\projects\assertiontestingproject\assertiontestspec\bin\debug\assertiontestspec.dll" id="1f99eec5-9f6c-67d1-8553-a609633542c9">
      <Execution id="2ebcd21e-7486-4d64-a117-9dc60e79419c" />
      <TestMethod codeBase="c:/users/jacob/documents/visual studio 2010/Projects/AssertionTestingProject/AssertionTestSpec/bin/Debug/AssertionTestSpec.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="AssertionTestSpec.AssertionTestClassTest, AssertionTestSpec, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TestAssertFailedExceptions" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="1f99eec5-9f6c-67d1-8553-a609633542c9" executionId="2ebcd21e-7486-4d64-a117-9dc60e79419c" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="2ebcd21e-7486-4d64-a117-9dc60e79419c" testId="1f99eec5-9f6c-67d1-8553-a609633542c9" testName="TestAssertFailedExceptions" computerName="MANTA" duration="00:00:00.0122817" startTime="2014-01-17T10:59:30.0993177-06:00" endTime="2014-01-17T10:59:30.2234051-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="2ebcd21e-7486-4d64-a117-9dc60e79419c">
      <Output>
        <ErrorInfo>
          <Message>We must own our failures, and this failure is my own!</Message>
          <StackTrace>   at AssertionTestSpec.AssertionTestClassTest.TestAssertFailedExceptions() in c:\users\jacob\documents\visual studio 2010\Projects\AssertionTestingProject\AssertionTestSpec\AssertionTestClassTest.cs:line 81
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>